### PR TITLE
add webpacker gem

### PR DESCRIPTION
**Pull request by simleap**
- add webpacker gem
- use es6

### CODE REVIEW

**Comment by samnang** [comment]
@simleap test failed!

**Comment by simleap** [comment]
@samnang, i asked you to help me checking on this in slack haha.

**Comment by simleap** [comment]
@samnang, it is fixed.

**Comment by dwilkie** [comment]
@simleap what's this file for? https://github.com/somleng/somleng-scfm/blob/8c8a3ba979041e8141d46005457959e7819502fa/storage/fh/2C/fh2C894qLJ4AXLYBAFkgy4KL

**Comment by simleap** [comment]
@dwilkie, that is file uploaded from local that is my bad didn't see in git log because it's too big. On PIN  local storage is "tmp/storage", so should i change it to tmp folder or just git ignore storage folder?

**Comment by samnang** [comment]
@dependabot rebase

**Comment by samnang** [comment]
@simleap are there any additional steps to setup or run it? If so, could you also add into readme.

**Comment by simleap** [comment]
@dwilkie, i thought travis will handle that. i have no idea about Elastic Beanstalk.

**Comment by samnang** [comment]
@dwilkie @simleap I think we already have `yarn` installed https://github.com/somleng/somleng-scfm/blob/develop/.ebextensions/yarn.config

The only missing is the configuration in nginx to make it to be able to serve static files under `/pack`:

```patch
diff --git a/.ebextensions/90_nginx_setup.config b/.ebextensions/90_nginx_setup.config
index ccb08e4..3e0af1d 100644
--- a/.ebextensions/90_nginx_setup.config
+++ b/.ebextensions/90_nginx_setup.config
@@ -21,12 +21,14 @@ files:
         cat $webapp_config_file.default | \
           tr '\n' '\r' | sed -e "s/\(location\s\+\/assets\s\+{\r[^}]*\)\(\s\{2\}}\)/\1    include \/etc\/nginx\/conf.d\/cors_fonts; # $CONFIGURATION_COMMENT\r\2/" | tr '\r' '\n' | \
           tr '\n' '\r' | sed -e "s/\(location\s\+\/\s\+{\r[^}]*}\)/\1\r\r  include \/etc\/nginx\/conf.d\/health_checks; # $CONFIGURATION_COMMENT/" | tr '\r' '\n' | \
+          tr '\n' '\r' | sed -e "s/\(location\s\+\/\s\+{\r[^}]*}\)/\1\r\r  include \/etc\/nginx\/conf.d\/webpacker; # $CONFIGURATION_COMMENT/" | tr '\r' '\n' | \
           tr '\n' '\r' | sed -e "1s/^/include \/etc\/nginx\/conf.d\/nginx_proto_map; # $CONFIGURATION_COMMENT\r\r/" | tr '\r' '\n' > $webapp_config_file
       done
 
       ln -sf $EB_SUPPORT_DIR/conf/cors_fonts /etc/nginx/conf.d/
       ln -sf $EB_SUPPORT_DIR/conf/bongloy_js /etc/nginx/conf.d/
       ln -sf $EB_SUPPORT_DIR/conf/health_checks /etc/nginx/conf.d/
+      ln -sf $EB_SUPPORT_DIR/conf/webpacker /etc/nginx/conf.d/
       ln -sf $EB_SUPPORT_DIR/conf/nginx_proto_map /etc/nginx/conf.d/
 
       service nginx restart
@@ -48,6 +50,20 @@ files:
         proxy_set_header X-Forwarded-Proto $http_proto;
       }
 
+  "/opt/elasticbeanstalk/support/conf/webpacker":
+    mode: "000644"
+    content: |
+      location /packs {
+        if ($http_x_forwarded_proto != 'https') {
+          return 301 https://$host$request_uri;
+        }
+        alias /var/app/current/public/packs;
+        gzip_static on;
+        gzip on;
+        expires max;
+        add_header Cache-Control public;
+      }
+
   "/opt/elasticbeanstalk/support/conf/nginx_proto_map":
     mode: "000644"
     content: |
```

**Pull request closed without merging**
